env:
  global:
    - DOCKER_REPO=quay.io/kubevirt

language: go
go_import_path: kubevirt.io/hostpath-provisioner
go:
- 1.13.1
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- make test

before_deploy:
  - docker login quay.io -u="$QUAY_USER" -p="$QUAY_PASS"

deploy:
# Release :latest images
- provider: script
  env:
    - TAG=latest
  script: make push
  skip_cleanup: true
  on:
    branch: master
    repo: kubevirt/hostpath-provisioner
# Release versioned images
- provider: script
  script: TAG=$TRAVIS_TAG make push
  branches:
    only: /v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+){0,1}/
  on:
    tags: true
    repo: kubevirt/hostpath-provisioner
- provider: releases
  branches:
    only: /v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+){0,1}/
  on:
    tags: true
    repo: kubevirt/hostpath-provisioner
  api_key:
    secure: "AC9QTK/z2DEw9TXK9+9tqc871YkZXIunpBYvLean+57mnE31LgxE3+YfLIFXOzufxEY9PuGInbuzhiXuhivt+mXusb6XKJ9lif2iVwEESJyxugK5TonhVGvCvxPUFbqKYOXvns4Ac+Sn5eTg2Mh64CqA2F2wpX9krYDJjfXy+GeJWwFQ/42WCW99+lVXCuDqBvQ9TNhWDhkf/LKapEylS2FlYTXXOU9QrnLGN4y9JXwpA/UsoOwQH4KkdrKnubfLQBwppbw5vdu1pGkJWuv0SEUaPkk2VZ4ZFZa2aUO47p1s9cQmlcnH2VCJbwTCOZmmhpq5uR8WrD6a4BaxFz+e0UeoiSBsIhRztQuUJmwUrz2PPTpjq9SmvLRX3YVnFX3/ETB7jSNwKJMnCKyj4a3vXDexOa+wIWDctGUZ8LbMC7I2dXVY0UDgQ/T/Elz373kz4Rf6IGhLBy39qvKgqhdAbNhZQboWVhMTkn+EZYlBOKlbt3HHuPpHbyt/AdPCgOin4ay0Df2TuXmeuVqO+LV5Ji7MgE+/gylVCLpQ9QH/XEs7cR1DhE25edfl/Ajn05LLDH02ndf412GyEmExSZvJMJ5Rae48uonM0roYG4reDTSBp4ft8Bs2vlMAyNXR52qCzyjyoGYDrqyCq8jVyt2JuUPlxpwfnzhLHSz2/joRg1Y="
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - deploy/*.yaml

